version: '3'

services:

  minio:
    image: minio/minio
    hostname: minio
    networks:
      - common
    volumes:
      - data1:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

networks:
  common:
    driver: bridge

volumes:
  data1: